apiVersion: v1
kind: Pod
metadata:
   name: multiple-command-pod
spec:
   containers:
   - name: ubuntu-container
     image: ubuntu:latest
     command: ["/bin/sh", "-c"]
     args: ["echo \"Hello from the container!\";sleep 10;echo \"Hello again!\";sleep 3600"]