#
# Service for exposing a port inside of the cluster
#
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc               # service name
spec:
  type: ClusterIP                   # type of the service (exposing port inside of a cluster)
  selector:                         # selection of pods
    app: clusterip                  # that belong to the service
  ports:
  - protocol: TCP
    port: 80                        # port exposed by the service
    targetPort: 8080                # port exposed by the pods
