#
# Ingress for routing of requests
# to the corresponded services
# All requests with url /wolf will be 
#  routed to the wolf-svc:8080 service
#  Requests with url /rabbit will be
#  routed to rabbit-svc:8090
#  The rest goes to the default backend
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: my-ingress                 # name of the ingress object
spec:
   rules:
   - http:
      paths:
      - path: /wolf                 # route all /wolf requests to the wolf service
        backend:
         serviceName: wolf-svc      # name of the target service
         servicePort: 8080          # port of the target service
      - path: /rabbit               # route all /rabbit requests to the rabbit service
        backend:
         serviceName: rabbit-svc    # name of the target service
         servicePort: 8090          # port of the target service
---
#
# Default backend ingress to cach
# all requests that cannot be 
# properly routed
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: def-ingress
spec:
   backend:
      serviceName: def-backend-svc  # name of the default backend service
      servicePort: 8070             # port of the default backend service
